### ISSUE TITLE
[question] What value does this package add?

### ISSUE THREAD

**Issue by igneus** [localheinz/factory-muffin-definition#17]
Hi, this is rather a curious question, no real issue:

https://github.com/localheinz/factory-girl-definition is really useful when working with factory-girl-php, as factory-girl-php provides no mechanism for sharing of factory definitions. factory-muffin, however, [provides one](https://github.com/thephpleague/factory-muffin#real-examples). This package seems to duplicate it, or rather provide a more verbose interface for achieving the same goal. Do I miss some important feature added by factory-muffin-definition and not already present in factory-muffin itself?

**Comment by localheinz** [comment]
Thank you for asking!

Personally, I see the following advantages of using this package here instead of defining factories as suggested at https://github.com/thephpleague/factory-muffin/tree/v3.0.1#real-examples:

It allows me to define a concrete entity definition *per* entity (of course, one could define *multiple* entities within one implementation of `Localheinz\FactoryMuffin\Definition\Definition`, but I would advise against it).

Consequently, one could at least enforce the creation of such a definition by means of a project code test: similar to https://github.com/localheinz/test-util/blob/0.6.1/test/Unit/ProjectCodeTest.php#L29-L36, where I assert that a 1:1 mapping between production classes and unit tests exists, one could assert that an entity definition exists per entity. This is at least helpful when working with a lot of developers where not everyone is on the same page in regard to testing, and where you want to prevent / enforce some behaviour. 

That is actually the main idea of it, so of course, when a team works fine already, then there's not a big advantage.

As I pointed out in [`README.md`](https://github.com/localheinz/factory-muffin-definition/blob/1.1.0/README.md), this project was inspired by [`localheinz/factory-girl-definition`](https://github.com/localheinz/factory-girl-definition), and there, as you suggested, this really is useful as there is no such loading mechanism. 

Since I have used similar code in different projects (for example, I have used [`league/factory-muffin`](https://github.com/thephpleague/factory-muffin) in a legacy project with [`kohana/orm`](https://github.com/kohana/orm), and there I similarly had tests which asserted that entity definitions existed), and since it didn't require a lot of work to implement, I figured I could just provide this - very small - package here for someone who has similar issues.

Glad you like `localheinz/factory-girl-definition`, that is great to hear!

Feel free to let me know if you any more questions, @igneus!

**Comment by localheinz** [comment]
@igneus 

What do you think, would it be worth pointing this out in `README.md`?

**Comment by igneus** [comment]
@localheinz Thanks for the reply. I didn't realize factory-muffin-definition could be not only a definition sharing solution, but also an "adapter" for another tool like `ProjectCodeTest`. It may be worth mentioning in the README.

> Glad you like localheinz/factory-girl-definition, that is great to hear!

Sadly, I'm going to migrate away from factory-girl-php altogether, as it's not mature enough for my use cases. factory-muffin looks very promissing.

(My question has been answered, so I guess I can close the issue.)
